services:
  prov1:
    build:
      dockerfile: Dockerfile
      context: ../../yagna_requestor_node
      args:
        - YAGNA_BRANCH_OR_TAG=${YAGNA_BRANCH_OR_TAG}
        - YAGNA_GIT_CLONE_CACHE_TOKEN=${YAGNA_GIT_CLONE_CACHE_TOKEN}
        - YAGNA_INCREMENTAL_BUILD_TOKEN=${YAGNA_INCREMENTAL_BUILD_TOKEN}
    env_file:
      - common_config.env
      - prov1.env
  prov2:
    build:
      dockerfile: Dockerfile
      context: ../../yagna_requestor_node
      args:
        - YAGNA_BRANCH_OR_TAG=${YAGNA_BRANCH_OR_TAG}
        - YAGNA_GIT_CLONE_CACHE_TOKEN=${YAGNA_GIT_CLONE_CACHE_TOKEN}
        - YAGNA_INCREMENTAL_BUILD_TOKEN=${YAGNA_INCREMENTAL_BUILD_TOKEN}
    env_file:
      - common_config.env
      - prov2.env
